# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: git-statuses
builds:
  - id: default
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
    main: ./cmd/git-statuses
    binary: git-statuses
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    hooks:
      post:
        - make man VERSION={{.Version}} COMMIT={{.ShortCommit}} DATE={{.Date}}
brews:
  - install: |
      bin.install "git-statuses"
      man1.install Dir.glob('git-statuses*.1')
    repository:
      owner: kyoh86
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/kyoh86/git-statuses
    description: Finds local git repositories and show statuses of them
    license: MIT
nfpms:
  - builds:
      - default
    maintainer: kyoh86 <me@kyoh86.dev>
    homepage: https://github.com/kyoh86/git-statuses
    description: Finds local git repositories and show statuses of them
    license: MIT
    formats:
      - apk
      - deb
      - rpm
archives:
  - id: gzip
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
      - git-statuses*.1
